version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  subscription-service:
    build: .
    command: ["./subscription-service"]
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres  

volumes:
  pgdata: